import { InputError } from './index.js';

const finite = (value, name) => { if (typeof value !== 'number' || !Number.isFinite(value)) throw new InputError(`${name} must be a finite number.`); };
const positive = (value, name) => { finite(value, name); if (value <= 0) throw new InputError(`${name} must be greater than zero.`); };
const tTables = { 90: { 1: 6.314, 2: 2.920, 3: 2.353, 4: 2.132, 5: 2.015, 6: 1.943, 7: 1.895, 8: 1.860, 9: 1.833, 10: 1.812, 12: 1.782, 14: 1.761, 16: 1.746, 18: 1.734, 20: 1.725, 25: 1.708, 30: 1.697, 40: 1.684, 50: 1.676, 60: 1.671, 80: 1.664, 100: 1.660, 120: 1.658, 200: 1.653, 500: 1.648 }, 95: { 1: 12.706, 2: 4.303, 3: 3.182, 4: 2.776, 5: 2.571, 6: 2.447, 7: 2.365, 8: 2.306, 9: 2.262, 10: 2.228, 12: 2.179, 14: 2.145, 16: 2.120, 18: 2.101, 20: 2.086, 25: 2.060, 30: 2.042, 40: 2.021, 50: 2.009, 60: 2.000, 80: 1.990, 100: 1.984, 120: 1.980, 200: 1.972, 500: 1.965 }, 99: { 1: 63.657, 2: 9.925, 3: 5.841, 4: 4.604, 5: 4.032, 6: 3.707, 7: 3.499, 8: 3.355, 9: 3.250, 10: 3.169, 12: 3.055, 14: 2.977, 16: 2.921, 18: 2.878, 20: 2.845, 25: 2.787, 30: 2.704, 40: 2.678, 50: 2.678, 60: 2.660, 80: 2.639, 100: 2.626, 120: 2.617, 200: 2.601, 500: 2.586 } };
const frontendTValue = (confidenceLevel, degreesOfFreedom) => { const df = Math.min(Math.max(Math.round(degreesOfFreedom), 1), 500); return tTables[confidenceLevel][Object.keys(tTables[confidenceLevel]).map(Number).reduce((closest, candidate) => Math.abs(candidate - df) < Math.abs(closest - df) ? candidate : closest)]; };

export function breakEvenPricing(input) {
  ['fixedCosts', 'pricePerUnit', 'variableCostPerUnit', 'expectedSales', 'demandIntercept', 'demandSlope'].forEach((field) => finite(input[field], field)); positive(input.demandIntercept, 'demandIntercept'); positive(input.demandSlope, 'demandSlope');
  if (!['0', '1', '2-5', '6+'].includes(input.competitorCount) || !['yes', 'no'].includes(input.differentiated) || !['price', 'quantity'].includes(input.competitionFocus) || !['yes', 'no'].includes(input.barrierToEntry) || typeof input.useRecommendations !== 'boolean') throw new InputError('Market structure options are invalid.');
  const structure = input.competitorCount === '0' || input.competitorCount === '1' ? 'Monopoly' : input.competitorCount === '2-5' ? input.competitionFocus === 'quantity' ? 'Cournot Oligopoly' : 'Bertrand Oligopoly' : input.barrierToEntry === 'yes' ? 'Monopolistic Competition' : 'Perfect Competition'; const firms = { '0': 1, '1': 1, '2-5': 3, '6+': 6 }[input.competitorCount]; let equilibriumPrice; let equilibriumQuantity;
  if (structure === 'Monopoly') { equilibriumQuantity = Math.max(0, (input.demandIntercept - input.variableCostPerUnit) / (2 * input.demandSlope)); equilibriumPrice = Math.max(0, input.demandIntercept - input.demandSlope * equilibriumQuantity); }
  else if (structure === 'Cournot Oligopoly') { const eachFirm = Math.max(0, (input.demandIntercept - input.variableCostPerUnit) / (input.demandSlope * (firms + 1))); equilibriumQuantity = firms * eachFirm; equilibriumPrice = Math.max(0, input.demandIntercept - input.demandSlope * equilibriumQuantity); }
  else if (structure === 'Bertrand Oligopoly' && input.differentiated === 'no') { equilibriumPrice = input.variableCostPerUnit; equilibriumQuantity = Math.max(0, (input.demandIntercept - equilibriumPrice) / input.demandSlope); }
  else if (structure === 'Bertrand Oligopoly') { equilibriumPrice = Math.max(0, (input.demandIntercept + firms * input.variableCostPerUnit) / (firms + 1)); equilibriumQuantity = Math.max(0, (input.demandIntercept - equilibriumPrice) / input.demandSlope); }
  else if (structure === 'Perfect Competition') { equilibriumPrice = input.variableCostPerUnit; equilibriumQuantity = Math.max(0, (input.demandIntercept - equilibriumPrice) / input.demandSlope); }
  else { const discriminant = Math.max(0, (input.demandIntercept - input.variableCostPerUnit) ** 2 - 4 * input.demandSlope * input.fixedCosts); equilibriumQuantity = discriminant > 0 ? Math.max(0, ((input.demandIntercept - input.variableCostPerUnit) + Math.sqrt(discriminant)) / (2 * input.demandSlope)) : Math.max(0, (input.demandIntercept - input.variableCostPerUnit * 1.2) / input.demandSlope); equilibriumPrice = discriminant > 0 ? Math.max(0, input.demandIntercept - input.demandSlope * equilibriumQuantity) : input.variableCostPerUnit * 1.2; }
  const price = input.useRecommendations ? equilibriumPrice : input.pricePerUnit; const quantity = input.useRecommendations ? equilibriumQuantity : input.expectedSales; if (price < input.variableCostPerUnit) throw new InputError('Sale price per unit must be greater than variable cost per unit to be profitable.'); const contributionMargin = price - input.variableCostPerUnit; const infiniteBreakEven = contributionMargin === 0; const breakEvenQuantity = infiniteBreakEven ? null : input.fixedCosts / contributionMargin; const expectedRevenue = price * quantity; return { structure, equilibriumPrice, equilibriumQuantity, recommendedPrice: equilibriumPrice, recommendedQuantity: equilibriumQuantity, contributionMargin, breakEvenQuantity, breakEvenRevenue: infiniteBreakEven ? 0 : breakEvenQuantity * price, marginOfSafetyUnits: infiniteBreakEven || quantity <= 0 ? null : quantity - breakEvenQuantity, marginOfSafetyPercent: infiniteBreakEven || quantity <= 0 ? null : (quantity - breakEvenQuantity) / quantity * 100, expectedRevenue, expectedProfit: contributionMargin * quantity - input.fixedCosts, perfectCompetitionEquilibrium: infiniteBreakEven && input.useRecommendations, isValid: true };
}

export function capmPortfolio(input) {
  ['riskFreeRate', 'marketReturn', 'marketStdDev', 'betaA', 'muA', 'sigmaA', 'betaB', 'muB', 'sigmaB', 'correlation', 'weightA'].forEach((field) => finite(input[field], field)); positive(input.sigmaA, 'sigmaA'); positive(input.sigmaB, 'sigmaB'); if (input.marketStdDev < 0 || input.correlation < -1 || input.correlation > 1 || input.weightA < 0 || input.weightA > 1) throw new InputError('marketStdDev must be non-negative; correlation and weightA must be between valid bounds.');
  const portfolio = (weight) => { const weightB = 1 - weight; const expectedReturn = weight * input.muA + weightB * input.muB; const variance = weight ** 2 * input.sigmaA ** 2 + weightB ** 2 * input.sigmaB ** 2 + 2 * weight * weightB * input.sigmaA * input.sigmaB * input.correlation; const stdDev = Math.sqrt(variance); return { weight, expectedReturn, stdDev, sharpe: stdDev === 0 ? 0 : (expectedReturn - input.riskFreeRate) / stdDev }; }; const efficientFrontier = Array.from({ length: 101 }, (_, index) => portfolio(index / 100)); const current = portfolio(input.weightA); const capmA = input.riskFreeRate + input.betaA * (input.marketReturn - input.riskFreeRate); const capmB = input.riskFreeRate + input.betaB * (input.marketReturn - input.riskFreeRate);
  return { capmA, capmB, alphaA: input.muA - capmA, alphaB: input.muB - capmB, portfolioReturn: current.expectedReturn, portfolioBeta: input.weightA * input.betaA + (1 - input.weightA) * input.betaB, portfolioStdDev: current.stdDev, sharpeA: (input.muA - input.riskFreeRate) / input.sigmaA, sharpeB: (input.muB - input.riskFreeRate) / input.sigmaB, sharpePortfolio: current.sharpe, efficientFrontier, optimalPortfolio: efficientFrontier.reduce((best, item) => item.sharpe > best.sharpe ? item : best), minVariance: efficientFrontier.reduce((best, item) => item.stdDev < best.stdDev ? item : best) };
}

export function simpleRegression(input) {
  if (!Array.isArray(input.dataPoints) || input.dataPoints.length < 3) throw new InputError('dataPoints must contain at least 3 observations.'); if (!Number.isInteger(input.forecastHorizon) || input.forecastHorizon < 0) throw new InputError('forecastHorizon must be a non-negative integer.'); if (![90, 95, 99].includes(input.confidenceLevel)) throw new InputError('confidenceLevel must be 90, 95, or 99.'); input.dataPoints.forEach((point, index) => { if (!point || typeof point !== 'object') throw new InputError(`dataPoints[${index}] must be an object.`); finite(point.x, `dataPoints[${index}].x`); finite(point.y, `dataPoints[${index}].y`); });
  const n = input.dataPoints.length; const xBar = input.dataPoints.reduce((sum, point) => sum + point.x, 0) / n; const yBar = input.dataPoints.reduce((sum, point) => sum + point.y, 0) / n; const denominator = input.dataPoints.reduce((sum, point) => sum + (point.x - xBar) ** 2, 0); if (denominator === 0) throw new InputError('dataPoints must contain more than one x value.'); const slope = input.dataPoints.reduce((sum, point) => sum + (point.x - xBar) * (point.y - yBar), 0) / denominator; const intercept = yBar - slope * xBar; const residuals = input.dataPoints.map((point) => ({ x: point.x, actual: point.y, predicted: intercept + slope * point.x, residual: point.y - (intercept + slope * point.x) })); const sse = residuals.reduce((sum, item) => sum + item.residual ** 2, 0); const sst = input.dataPoints.reduce((sum, point) => sum + (point.y - yBar) ** 2, 0); const standardErrorEstimate = Math.sqrt(sse / (n - 2)); const standardErrorSlope = standardErrorEstimate / Math.sqrt(denominator); const standardErrorIntercept = standardErrorEstimate * Math.sqrt(1 / n + xBar ** 2 / denominator); const tValue = frontendTValue(input.confidenceLevel, n - 2); const forecasts = Array.from({ length: input.forecastHorizon }, (_, index) => { const x = input.dataPoints.at(-1).x + index + 1; const y = intercept + slope * x; const marginOfError = tValue * standardErrorEstimate * Math.sqrt(1 + 1 / n + (x - xBar) ** 2 / denominator); return { x, y, lowerBound: y - marginOfError, upperBound: y + marginOfError, marginOfError }; }); const lineData = [{ x: Math.min(...input.dataPoints.map((point) => point.x), ...forecasts.map((item) => item.x)), y: intercept + slope * Math.min(...input.dataPoints.map((point) => point.x), ...forecasts.map((item) => item.x)) }, { x: Math.max(...input.dataPoints.map((point) => point.x), ...forecasts.map((item) => item.x)), y: intercept + slope * Math.max(...input.dataPoints.map((point) => point.x), ...forecasts.map((item) => item.x)) }]; return { isValid: true, slope, intercept, rSquared: sst === 0 ? 1 : 1 - sse / sst, forecasts, lineData, residuals, sse, sst, standardErrorEstimate, standardErrorSlope, tStatisticSlope: slope / standardErrorSlope, slopeCI: { lower: slope - tValue * standardErrorSlope, upper: slope + tValue * standardErrorSlope }, interceptCI: { lower: intercept - tValue * standardErrorIntercept, upper: intercept + tValue * standardErrorIntercept }, tValue, degreesOfFreedom: n - 2, n, xBar, denominator, meanX: xBar };
}

export function multipleRegression(input) {
  if (!Array.isArray(input.data) || input.data.length < 4) throw new InputError('data must contain at least 4 observations.'); if (!Number.isInteger(input.forecastHorizon) || input.forecastHorizon < 0) throw new InputError('forecastHorizon must be a non-negative integer.'); input.data.forEach((row, index) => ['x1', 'x2', 'y'].forEach((field) => finite(row?.[field], `data[${index}].${field}`))); const matrix = input.data.map((row) => [1, row.x1, row.x2]); const transpose = matrix[0].map((_, column) => matrix.map((row) => row[column])); const multiply = (left, right) => left.map((row) => right[0].map((_, column) => row.reduce((sum, value, index) => sum + value * right[index][column], 0))); const xtx = multiply(transpose, matrix); const [a,b,c] = xtx[0]; const [d,e,f] = xtx[1]; const [g,h,i] = xtx[2]; const determinant = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g); if (determinant === 0) throw new InputError('Multicollinearity detected.'); const inverse = [[e*i-f*h,c*h-b*i,b*f-c*e],[f*g-d*i,a*i-c*g,b*g-a*h],[d*h-e*g,d*b-a*f,a*e-b*d]].map((row) => row.map((value) => value / determinant)); const beta = multiply(multiply(inverse, transpose), input.data.map((row) => [row.y])).map((row) => row[0]); const predicted = matrix.map((row) => beta[0] + beta[1] * row[1] + beta[2] * row[2]); const yBar = input.data.reduce((sum, row) => sum + row.y, 0) / input.data.length; const sse = input.data.reduce((sum, row, index) => sum + (row.y - predicted[index]) ** 2, 0); const sst = input.data.reduce((sum, row) => sum + (row.y - yBar) ** 2, 0); const rSquared = sst === 0 ? 1 : 1 - sse / sst; const n = input.data.length; const df = n - 3; const ser = Math.sqrt(sse / df); let x1 = input.forecastInputs?.x1; let x2 = input.forecastInputs?.x2; finite(x1, 'forecastInputs.x1'); finite(x2, 'forecastInputs.x2'); finite(input.forecastInputs.x1Growth, 'forecastInputs.x1Growth'); finite(input.forecastInputs.x2Growth, 'forecastInputs.x2Growth'); const forecastSeries = Array.from({ length: input.forecastHorizon }, (_, index) => { const y = beta[0] + beta[1] * x1 + beta[2] * x2; const item = { period: index + 1, x1, x2, y }; x1 *= 1 + input.forecastInputs.x1Growth; x2 *= 1 + input.forecastInputs.x2Growth; return item; }); return { beta, rSquared, adjustedR2: 1 - (1 - rSquared) * (n - 1) / df, ser, sse, sst, n, k: 2, df, residuals: input.data.map((row, index) => ({ x: index + 1, actual: row.y, predicted: predicted[index], residual: row.y - predicted[index] })), forecastSeries };
}

export function portfolioAnalysis(input) {
  if (!Array.isArray(input.assets) || input.assets.length < 2) throw new InputError('assets must contain at least 2 assets.'); if (!Array.isArray(input.weights) || input.weights.length !== input.assets.length) throw new InputError('weights must match assets.'); finite(input.riskFreeRate, 'riskFreeRate'); input.assets.forEach((asset, index) => { finite(asset.expectedReturn, `assets[${index}].expectedReturn`); positive(asset.volatility, `assets[${index}].volatility`); finite(asset.beta, `assets[${index}].beta`); }); input.weights.forEach((weight, index) => finite(weight, `weights[${index}]`)); if (Math.abs(input.weights.reduce((sum, weight) => sum + weight, 0) - 1) >= 0.001) throw new InputError('weights must sum to 1 within 0.001.'); if (!Array.isArray(input.correlationMatrix) || input.correlationMatrix.length !== input.assets.length) throw new InputError('correlationMatrix dimensions must match assets.'); input.correlationMatrix.forEach((row, index) => { if (!Array.isArray(row) || row.length !== input.assets.length) throw new InputError(`correlationMatrix[${index}] dimensions must match assets.`); row.forEach((value, column) => { finite(value, `correlationMatrix[${index}][${column}]`); if (value < -1 || value > 1) throw new InputError('correlation values must be between -1 and 1.'); }); }); const returns = input.assets.map((asset) => asset.expectedReturn / 100); const volatilities = input.assets.map((asset) => asset.volatility / 100); const metrics = (weights) => { const expectedReturn = weights.reduce((sum, weight, index) => sum + weight * returns[index], 0); const variance = weights.reduce((total, weight, i) => total + weights.reduce((rowTotal, otherWeight, j) => rowTotal + weight * otherWeight * volatilities[i] * volatilities[j] * input.correlationMatrix[i][j], 0), 0); const volatility = Math.sqrt(variance); return { expectedReturn, volatility, variance, sharpeRatio: volatility > 0 ? (expectedReturn - input.riskFreeRate / 100) / volatility : 0, returnToRiskRatio: volatility > 0 ? expectedReturn / volatility : 0 }; }; const currentMetrics = metrics(input.weights); const portfolioBeta = input.assets.reduce((sum, asset, index) => sum + input.weights[index] * asset.beta, 0); return { currentMetrics, portfolioBeta, portfolioCapmReturn: input.riskFreeRate / 100 + portfolioBeta * ((input.benchmarkReturn ?? 10) / 100 - input.riskFreeRate / 100), portfolioAlpha: currentMetrics.expectedReturn - (input.riskFreeRate / 100 + portfolioBeta * ((input.benchmarkReturn ?? 10) / 100 - input.riskFreeRate / 100)), assetsWithAlpha: input.assets.map((asset, index) => ({ ...asset, currentWeight: input.weights[index], alpha: asset.expectedReturn / 100 - (input.riskFreeRate / 100 + asset.beta * ((input.benchmarkReturn ?? 10) / 100 - input.riskFreeRate / 100)) })) };
}