export class InputError extends Error { constructor(message) { super(message); this.name = 'InputError'; } }

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const number = (value, name) => { if (typeof value !== 'number' || !Number.isFinite(value)) throw new InputError(`${name} must be a finite number.`); return value; };
const positive = (value, name) => { number(value, name); if (value <= 0) throw new InputError(`${name} must be greater than zero.`); return value; };
const numericArray = (value, name, min = 1) => { if (!Array.isArray(value) || value.length < min) throw new InputError(`${name} must contain at least ${min} values.`); value.forEach((item, index) => number(item, `${name}[${index}]`)); return value; };
const object = (value, name) => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new InputError(`${name} must be an object.`); return value; };

export function cashflowForecaster(input) {
  number(input.startingCash, 'startingCash'); if (typeof input.autoMode !== 'boolean') throw new InputError('autoMode must be a boolean.');
  let revenues; let expenses;
  if (input.autoMode) { ['baseRevenue', 'baseExpense', 'revenueGrowth', 'expenseGrowth'].forEach((field) => number(input[field], field)); revenues = Array.from({ length: 12 }, (_, index) => Math.round(input.baseRevenue * (1 + input.revenueGrowth / 100) ** index)); expenses = Array.from({ length: 12 }, (_, index) => Math.round(input.baseExpense * (1 + input.expenseGrowth / 100) ** index)); }
  else { numericArray(input.manualRevenues, 'manualRevenues', 12); numericArray(input.manualExpenses, 'manualExpenses', 12); if (input.manualRevenues.length !== 12 || input.manualExpenses.length !== 12) throw new InputError('manualRevenues and manualExpenses must each contain exactly 12 values.'); revenues = input.manualRevenues.map(Math.round); expenses = input.manualExpenses.map(Math.round); }
  let cash = input.startingCash; let totalRevenue = 0; let totalExpenses = 0; let negativeMonths = 0;
  const results = revenues.map((revenue, index) => { const expense = expenses[index]; const net = revenue - expense; cash += net; totalRevenue += revenue; totalExpenses += expense; if (cash < 0) negativeMonths += 1; return { month: months[index], monthIndex: index + 1, revenue, expense, net, cash: Math.round(cash), isNegativeCash: cash < 0, isNegativeNet: net < 0 }; });
  const minCash = Math.min(input.startingCash, ...results.map((item) => item.cash)); return { results, totalRevenue, totalExpenses, endingBalance: results[11].cash, netCashFlow: totalRevenue - totalExpenses, minCash, maxCash: Math.max(input.startingCash, ...results.map((item) => item.cash)), negativeMonths, hasRisk: negativeMonths > 0 || minCash < 0 };
}

export function scenarioTester(input) {
  ['startingCash', 'baseRevenue', 'baseExpense', 'revenueGrowth', 'expenseGrowth', 'revenueChange', 'expenseChange'].forEach((field) => number(input[field], field));
  const baseRevenues = Array.from({ length: 12 }, (_, index) => input.baseRevenue * (1 + input.revenueGrowth / 100) ** index); const baseExpenses = Array.from({ length: 12 }, (_, index) => input.baseExpense * (1 + input.expenseGrowth / 100) ** index);
  const calculate = (revenues, expenses) => { let cash = input.startingCash; return revenues.map((revenue, index) => { const expense = expenses[index]; const net = revenue - expense; cash += net; return { revenue, expense, net, cash }; }); };
  const baseCase = calculate(baseRevenues, baseExpenses); const scenarioCase = calculate(baseRevenues.map((value) => value * (1 + input.revenueChange / 100)), baseExpenses.map((value) => value * (1 + input.expenseChange / 100))); const baseEndingCash = baseCase[11].cash; const scenarioEndingCash = scenarioCase[11].cash; const cashImpact = scenarioEndingCash - baseEndingCash;
  return { baseCase, scenarioCase, comparisonData: months.map((month, index) => ({ month, baseCash: baseCase[index].cash, scenarioCash: scenarioCase[index].cash, delta: scenarioCase[index].cash - baseCase[index].cash })), impact: { baseEndingCash, scenarioEndingCash, cashImpact, cashImpactPercent: baseEndingCash !== 0 ? cashImpact / Math.abs(baseEndingCash) * 100 : scenarioEndingCash > 0 ? 100 : 0 } };
}

const payment = (principal, annualRate, termYears, paymentsPerYear) => { const periodicRate = annualRate / paymentsPerYear; const periods = termYears * paymentsPerYear; return periodicRate === 0 ? principal / periods : principal * (periodicRate * (1 + periodicRate) ** periods) / ((1 + periodicRate) ** periods - 1); };

export function loanAmortization(input) {
  ['principal', 'annualRate', 'termYears', 'paymentsPerYear', 'extraPayment'].forEach((field) => number(input[field], field)); positive(input.principal, 'principal'); positive(input.termYears, 'termYears'); positive(input.paymentsPerYear, 'paymentsPerYear'); if (input.annualRate < 0 || input.extraPayment < 0) throw new InputError('annualRate and extraPayment cannot be negative.');
  const periodicRate = input.annualRate / 100 / input.paymentsPerYear; const totalPeriods = Math.ceil(input.termYears * input.paymentsPerYear); const regularPayment = payment(input.principal, input.annualRate / 100, input.termYears, input.paymentsPerYear);
  const schedule = (extra) => { const rows = []; let balance = input.principal; let totalInterest = 0; for (let period = 1; period <= totalPeriods && balance > 0.01; period += 1) { const interest = balance * periodicRate; const principal = Math.min(regularPayment + extra - interest, balance); balance = Math.max(0, balance - principal); totalInterest += interest; rows.push({ period, payment: interest + principal, interest, principal, balance, totalInterest }); } return rows; };
  const regularSchedule = schedule(0); const extraSchedule = schedule(input.extraPayment); return { regularPayment, regularSchedule, extraSchedule, chartData: Array.from({ length: Math.max(regularSchedule.length, extraSchedule.length) }, (_, index) => ({ period: index + 1, regularBalance: regularSchedule[index]?.balance || 0, extraBalance: extraSchedule[index]?.balance || 0 })), regularTotalInterest: regularSchedule.at(-1)?.totalInterest || 0, extraTotalInterest: extraSchedule.at(-1)?.totalInterest || 0, timeSaved: regularSchedule.length - extraSchedule.length, interestSaved: (regularSchedule.at(-1)?.totalInterest || 0) - (extraSchedule.at(-1)?.totalInterest || 0) };
}

export function interestRateSensitivity(input) {
  ['principal', 'baseAPR', 'termYears', 'paymentsPerYear', 'testRange', 'stepSize'].forEach((field) => number(input[field], field)); positive(input.principal, 'principal'); positive(input.termYears, 'termYears'); positive(input.paymentsPerYear, 'paymentsPerYear'); positive(input.stepSize, 'stepSize'); if (input.baseAPR < 0 || input.testRange < 0) throw new InputError('baseAPR and testRange cannot be negative.');
  const basePayment = payment(input.principal, input.baseAPR / 100, input.termYears, input.paymentsPerYear); const baseTotalInterest = basePayment * input.termYears * input.paymentsPerYear - input.principal; const scenario = (apr) => { const scenarioPayment = payment(input.principal, apr / 100, input.termYears, input.paymentsPerYear); const totalInterest = scenarioPayment * input.termYears * input.paymentsPerYear - input.principal; return { apr, ear: (1 + (apr / 100) / input.paymentsPerYear) ** input.paymentsPerYear * 100 - 100, payment: scenarioPayment, totalInterest, paymentChange: (scenarioPayment - basePayment) / basePayment, interestChange: baseTotalInterest === 0 ? 0 : (totalInterest - baseTotalInterest) / baseTotalInterest, isBase: Math.abs(apr - input.baseAPR) < 0.001 }; };
  const minRate = Math.max(0.1, input.baseAPR - input.testRange); const maxRate = input.baseAPR + input.testRange; const scenarios = []; for (let index = 0; index <= Math.floor((maxRate - minRate) / input.stepSize); index += 1) { const rate = Number((minRate + index * input.stepSize).toFixed(3)); if (rate <= maxRate + 0.001) scenarios.push(scenario(rate)); } if (!scenarios.some((item) => item.isBase)) scenarios.push(scenario(input.baseAPR)); if (Math.abs(maxRate - scenarios.at(-1).apr) > 0.001) scenarios.push(scenario(maxRate)); return { basePayment, baseTotalInterest, scenarios: scenarios.sort((left, right) => left.apr - right.apr) };
}

const npv = (cashFlows, rate, periods) => { const adjustedRate = (1 + rate) ** (1 / periods) - 1; return cashFlows.reduce((total, cashFlow, period) => total + cashFlow / (1 + adjustedRate) ** period, 0); };
const irr = (cashFlows, periods) => { if (!cashFlows.some((value) => value < 0) || !cashFlows.some((value) => value > 0)) return null; let low = -0.99; let high = 20; if (npv(cashFlows, low, periods) * npv(cashFlows, high, periods) > 0) return null; for (let index = 0; index < 100; index += 1) { const middle = (low + high) / 2; const middleValue = npv(cashFlows, middle, periods); if (Math.abs(middleValue) < 1e-10 || Math.abs(high - low) < 1e-10) return middle; if (npv(cashFlows, low, periods) * middleValue < 0) high = middle; else low = middle; } return null; };

export function dcf(input) {
  numericArray(input.initialInvestments, 'initialInvestments'); numericArray(input.operatingCashFlows, 'operatingCashFlows'); number(input.salvageValue, 'salvageValue'); if (!['annual', 'quarterly', 'monthly'].includes(input.periodicity)) throw new InputError('periodicity must be annual, quarterly, or monthly.'); const periodsPerYear = { annual: 1, quarterly: 4, monthly: 12 }[input.periodicity]; let effectiveDiscountRate = input.discountRate;
  if (input.useWACC) { object(input.waccInputs, 'waccInputs'); ['costOfDebt', 'taxRate', 'costOfEquity', 'debtRatio'].forEach((field) => number(input.waccInputs[field], `waccInputs.${field}`)); effectiveDiscountRate = input.waccInputs.costOfDebt * (1 - input.waccInputs.taxRate) * input.waccInputs.debtRatio + input.waccInputs.costOfEquity * (1 - input.waccInputs.debtRatio); } number(effectiveDiscountRate, 'discountRate'); if (effectiveDiscountRate <= -1) throw new InputError('discountRate must be greater than -1.');
  const completeCashFlows = [...input.initialInvestments, ...input.operatingCashFlows.slice(0, -1), input.operatingCashFlows.at(-1) + input.salvageValue]; const netPresentValue = npv(completeCashFlows, effectiveDiscountRate, periodsPerYear); const internalRate = irr(completeCashFlows, periodsPerYear); const rate = (1 + effectiveDiscountRate) ** (1 / periodsPerYear) - 1; let cumulativeSimple = 0; let cumulativeDiscounted = 0; let simplePayback = null; let discountedPayback = null;
  const chartData = completeCashFlows.map((cashFlow, index) => { const discountedCashFlow = cashFlow / (1 + rate) ** index; const beforeSimple = cumulativeSimple; const beforeDiscounted = cumulativeDiscounted; cumulativeSimple += cashFlow; cumulativeDiscounted += discountedCashFlow; if (simplePayback === null && cumulativeSimple >= 0) simplePayback = index === 0 ? 0 : (index - 1 + Math.abs(beforeSimple) / cashFlow) / periodsPerYear; if (discountedPayback === null && cumulativeDiscounted >= 0) discountedPayback = index === 0 ? 0 : (index - 1 + Math.abs(beforeDiscounted) / discountedCashFlow) / periodsPerYear; return { period: index < input.initialInvestments.length ? `Inv-${input.initialInvestments.length - index}` : `${input.periodicity === 'annual' ? 'Y' : input.periodicity === 'quarterly' ? 'Q' : 'M'}${index - input.initialInvestments.length + 1}`, periodIndex: index, cashFlow, discountedCashFlow, cumulativeSimple, cumulativeDiscounted }; }); const recommendation = netPresentValue > 0 && internalRate !== null && internalRate > effectiveDiscountRate + 0.02 ? 'accept' : netPresentValue > 0 && internalRate !== null && internalRate > effectiveDiscountRate ? 'marginal' : 'reject'; return { effectiveDiscountRate, periodsPerYear, completeCashFlows, npv: netPresentValue, irr: internalRate, simplePayback, discountedPayback, chartData, recommendation };
}

export function workingCapitalCcc(input) {
  ['currentAssets', 'currentLiabilities', 'inventory', 'accountsReceivable', 'accountsPayable', 'annualCreditSales', 'annualCOGS', 'daysBasis'].forEach((field) => number(input[field], field)); if (![360, 365].includes(input.daysBasis)) throw new InputError('daysBasis must be 360 or 365.'); const dailySales = input.annualCreditSales > 0 ? input.annualCreditSales / input.daysBasis : 0; const dailyCOGS = input.annualCOGS > 0 ? input.annualCOGS / input.daysBasis : 0; const DSO = dailySales > 0 ? input.accountsReceivable / dailySales : null; const DIO = dailyCOGS > 0 ? input.inventory / dailyCOGS : null; const DPO = dailyCOGS > 0 ? input.accountsPayable / dailyCOGS : null; return { workingCapital: input.currentAssets - input.currentLiabilities, currentRatio: input.currentLiabilities > 0 ? input.currentAssets / input.currentLiabilities : null, quickRatio: input.currentLiabilities > 0 ? (input.currentAssets - input.inventory) / input.currentLiabilities : null, DSO, DIO, DPO, CCC: DSO === null || DIO === null || DPO === null ? null : DSO + DIO - DPO };
}

export function profitMaximization(input) {
  ['demandA', 'demandB', 'fixedCost', 'marginalCost'].forEach((field) => number(input[field], field)); positive(input.demandA, 'demandA'); positive(input.demandB, 'demandB'); if (input.marginalCost < 0) throw new InputError('marginalCost cannot be negative.'); if (input.demandA <= input.marginalCost) throw new InputError('demandA must be greater than marginalCost for profitable operation.'); const optimalQuantity = (input.demandA - input.marginalCost) / (2 * input.demandB); const optimalPrice = input.demandA - input.demandB * optimalQuantity; const totalRevenue = optimalPrice * optimalQuantity; const totalCost = input.fixedCost + input.marginalCost * optimalQuantity; const discriminant = (input.demandA - input.marginalCost) ** 2 - 4 * input.demandB * input.fixedCost; return { isValid: true, optimalQuantity, optimalPrice, totalRevenue, totalCost, maxProfit: totalRevenue - totalCost, marginalRevenue: input.demandA - 2 * input.demandB * optimalQuantity, elasticityAtOptimum: -(input.demandA + input.marginalCost) / (input.demandA - input.marginalCost), revenueMaximizingQ: input.demandA / (2 * input.demandB), breakEvenQuantities: discriminant < 0 ? [] : [((input.demandA - input.marginalCost) - Math.sqrt(discriminant)) / (2 * input.demandB), ((input.demandA - input.marginalCost) + Math.sqrt(discriminant)) / (2 * input.demandB)].filter((value) => value >= 0) };
}

export function optimalPricing(input) {
  number(input.marginalCost, 'marginalCost'); if (input.marginalCost <= 0) throw new InputError('marginalCost must be greater than 0 for a finite optimum.'); if (!['known_epsilon', 'estimate_epsilon'].includes(input.mode)) throw new InputError('mode must be known_epsilon or estimate_epsilon.'); let elasticity; let k; let calibPoint;
  if (input.mode === 'known_epsilon') { ['knownElasticity', 'calibP0', 'calibQ0'].forEach((field) => positive(input[field], field)); elasticity = Math.abs(input.knownElasticity); if (elasticity <= 1) throw new InputError('knownElasticity must be greater than 1 for a finite optimum.'); k = input.calibQ0 * input.calibP0 ** elasticity; calibPoint = { P: input.calibP0, Q: input.calibQ0 }; } else { ['p1', 'q1', 'p2', 'q2'].forEach((field) => positive(input[field], field)); if (input.p1 === input.p2) throw new InputError('p1 and p2 must be different to estimate elasticity.'); elasticity = -Math.log(input.q2 / input.q1) / Math.log(input.p2 / input.p1); if (elasticity <= 1) throw new InputError('Estimated elasticity must be greater than 1 for a finite optimum.'); k = input.q1 * input.p1 ** elasticity; calibPoint = { P: input.p1, Q: input.q1 }; }
  const optimalPrice = input.marginalCost / (1 - 1 / elasticity); const optimalQuantity = k * optimalPrice ** -elasticity; return { elasticity, k, optimalPrice, optimalQuantity, optimalRevenue: optimalPrice * optimalQuantity, optimalProfit: (optimalPrice - input.marginalCost) * optimalQuantity, markup: (optimalPrice - input.marginalCost) / optimalPrice, calibPoint };
}