import cors from 'cors';
import express from 'express';
import { InputError, cashflowForecaster, dcf, interestRateSensitivity, loanAmortization, optimalPricing, profitMaximization, scenarioTester, workingCapitalCcc } from './calculators/index.js';
import { breakEvenPricing, capmPortfolio, multipleRegression, portfolioAnalysis, simpleRegression } from './calculators/advanced.js';

const calculators = { 'cashflow-forecaster': { name: 'Cashflow Forecaster', calculate: cashflowForecaster }, 'break-even-pricing': { name: 'Break-Even and Pricing Strategy', calculate: breakEvenPricing }, 'scenario-tester': { name: 'Scenario Tester', calculate: scenarioTester }, 'loan-amortization': { name: 'Loan Amortization', calculate: loanAmortization }, dcf: { name: 'DCF Valuation Model', calculate: dcf }, 'interest-rate-sensitivity': { name: 'Interest Rate Sensitivity', calculate: interestRateSensitivity }, 'capm-portfolio': { name: 'CAPM and Portfolio Analyzer', calculate: capmPortfolio }, 'portfolio-analysis': { name: 'Portfolio Analysis Toolkit', calculate: portfolioAnalysis }, 'working-capital-ccc': { name: 'Working Capital CCC', calculate: workingCapitalCcc }, 'simple-regression': { name: 'Simple Linear Regression', calculate: simpleRegression }, 'multiple-regression': { name: 'Multiple Regression', calculate: multipleRegression }, 'profit-maximization': { name: 'Profit Maximization', calculate: profitMaximization }, 'optimal-pricing': { name: 'Optimal Pricing', calculate: optimalPricing } };

export function createApp() {
  const app = express(); const allowedOrigins = (process.env.FRONTEND_ORIGIN || 'http://localhost:5173').split(',').map((origin) => origin.trim()).filter(Boolean);
  app.use(cors({ origin(origin, callback) { if (!origin || allowedOrigins.includes(origin)) return callback(null, true); return callback(new InputError('Origin is not allowed by CORS policy.')); } })); app.use(express.json({ limit: '100kb' }));
  app.get('/api/health', (_request, response) => response.json({ status: 'ok', service: 'finflow-analytics-api' })); app.get('/api', (_request, response) => response.json({ name: 'FinFlow Analytics API', version: '1.0.0', calculators: Object.entries(calculators).map(([endpoint, calculator]) => ({ name: calculator.name, endpoint: `/api/${endpoint}`, method: 'POST' })) }));
  Object.entries(calculators).forEach(([endpoint, calculator]) => app.post(`/api/${endpoint}`, (request, response, next) => { try { response.json({ success: true, calculator: endpoint, result: calculator.calculate(request.body) }); } catch (error) { error.calculator = endpoint; next(error); } }));
  app.use((_request, _response, next) => next(Object.assign(new InputError('Route not found.'), { status: 404, code: 'NOT_FOUND' }))); app.use((error, _request, response, _next) => { const invalidJson = error instanceof SyntaxError && Object.hasOwn(error, 'body'); const status = error.status || (invalidJson || error instanceof InputError ? 400 : 500); response.status(status).json({ success: false, calculator: error.calculator || null, error: { code: error.code || (invalidJson || error instanceof InputError ? 'INVALID_INPUT' : 'INTERNAL_ERROR'), message: invalidJson ? 'Request body must be valid JSON.' : error instanceof InputError ? error.message : 'An unexpected error occurred.' } }); }); return app;
}